apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: addonrizky.com
    external-dns.alpha.kubernetes.io/ttl: "120" #optional
spec:
  type: LoadBalancer
  selector:
    app: rtmp-server
  ports:
  - protocol: TCP
    port: 1935
    targetPort: 1935